/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["footer._huato_BG_hotphone\r\n  margin-top: 12px\r\n  background: url('../../../assets/image/product/layout/Product-center-phone-background.png')\r\n  background-size: 100%\r\n  background-repeat: no-repeat\r\n  height: 284px\r\n  text-align: center\r\n  display: -webkit-box\r\n  display: -ms-flexbox\r\n  display: -webkit-flex\r\n  display: flex\r\n  -webkit-box-pack: center\r\n  -ms-flex-pack: center\r\n  -webkit-justify-content: center\r\n  justify-content: center\r\n  -webkit-box-align: center\r\n  -ms-flex-align: center\r\n  -webkit-align-items: center\r\n  align-items: center\r\n  >section\r\n    >h2\r\n      height: 34px\r\n      line-height: 34px\r\n      color: #ffffff\r\n      font-family: Microsoft YaHei\r\n      text-align: center\r\n      font-size: 26px\r\n    >p\r\n      font-size: 12px\r\n      color: #04699d\r\n      height: 20px\r\n      line-height: 20px\r\n    >h3\r\n      height: 50px\r\n      line-height: 50px\r\n      color: #fff\r\n      font-size: 30px\r\n      font-weight: bold\r\n      font-family: Arial\r\n    >span\r\n      font-size: 14px\r\n      font-family: Microsoft YaHei\r\n      color: rgba(255,255,255,.7)\r\n      line-height: 28px"];
export { styles as styles };
