/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["._huato_layout_header,\r\n._huato_layout_content,\r\n._huato_layout_footer\r\n  padding: 0\r\n  margin: 0\r\n  height: initial\r\n  line-height: initial\r\n  background: #fff\r\n._huato_layout_logger\r\n  height: 100px\r\n  overflow: hidden\r\n  >section\r\n    margin: 30px auto\r\n\r\n._huato_hotline\r\n  display: inline-block\r\n  zoom: 1\r\n  height: 40px\r\n  >img\r\n    margin-right: 80px\r\n  span\r\n    font-size: 14px\r\n    color: #414549\r\n    display: block\r\n    height: 16px\r\n    text-align: left\r\n  h2\r\n    font-size: 26px\r\n    color: #3498ee\r\n    text-align: left\r\n    font-weight: bold\r\n    font-family: Microsoft YaHei\r\n._huato_layout_nav\r\n  background: #5BADF2\r\n  height: 50px\r\n  line-height: 50px\r\n  >nav\r\n    display: block\r\n    margin: 0 auto\r\n    >menu\r\n      padding: 0 40px\r\n      color: #fff\r\n      font-size: 16px \r\n      font-family: Microsoft YaHei\r\n      display: inline-block\r\n      cursor: pointer\r\n      outline: none\r\n    >menu:hover\r\n      background: rgb(37,126,201)\r\n    >menu.active\r\n      background: rgb(37,126,201)"];
export { styles as styles };
