/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["._huato_product_banner\r\n  width: 100%\r\n  min-width: 1200px\r\n  font-size: 0\r\n  >img\r\n    width: 100%"];
export { styles as styles };
