/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["._huato_product_center\r\n  display: block\r\n  >section\r\n    margin: 0 auto\r\n    ._huato_product_list_menu\r\n      width: 294px\r\n      display: inline-block\r\n      header\r\n        font-size: 0\r\n        img\r\n          width: 100%\r\n    ._huato_product_list_details\r\n      display: inline-block\r\n      width: 906px"];
export { styles as styles };
